// src/services/ogValidatorService.ts
import axios from "axios";

const API_BASE_URL =
  process.env.REACT_APP_API_BASE_URL || "https://zp9kzmug2t.ap-southeast-2.awsapprunner.com/api";

export interface OGTag {
  [key: string]: string;
}

export interface ImageValidation {
  valid: boolean;
  width?: number;
  height?: number;
  aspectRatio?: number;
  isRecommendedSize?: boolean;
  isRecommendedAspectRatio?: boolean;
  message: string;
  error?: string;
}

export interface ValidationSummary {
  totalTags: number;
  requiredTagsPresent: number;
  requiredTagsTotal: number;
  errorsCount: number;
  warningsCount: number;
}

export interface DebugTools {
  facebook: string;
  linkedin: string;
  twitter: string;
}

export interface ValidationReport {
  isValid: boolean;
  url: string;
  errors: string[];
  warnings: string[];
  recommendations: string[];
  tags: OGTag;
  imageValidation: ImageValidation | null;
  debugTools: DebugTools;
  summary: ValidationSummary;
  timestamp: string;
}

export interface ValidationResponse {
  success: boolean;
  data?: ValidationReport;
  error?: string;
}

/**
 * Validate Open Graph tags for a given URL
 */
export const validateOpenGraph = async (
  url: string
): Promise<ValidationReport> => {
  try {
    const response = await axios.post<ValidationResponse>(
      `${API_BASE_URL}/og-validator/validate`,
      { url },
      {
        headers: {
          "Content-Type": "application/json",
        },
        timeout: 30000, // 30 second timeout
      }
    );

    if (!response.data.success || !response.data.data) {
      throw new Error(response.data.error || "Validation failed");
    }

    return response.data.data;
  } catch (error: any) {
    if (axios.isAxiosError(error)) {
      if (error.response) {
        throw new Error(
          error.response.data?.error || `Server error: ${error.response.status}`
        );
      } else if (error.request) {
        throw new Error(
          "Unable to connect to validation service. Please check if the server is running."
        );
      }
    }
    throw new Error(error.message || "An unexpected error occurred");
  }
};

/**
 * Check OG Validator API health
 */
export const checkOGValidatorHealth = async (): Promise<boolean> => {
  try {
    const response = await axios.get(`${API_BASE_URL}/og-validator/health`, {
      timeout: 5000,
    });
    return response.data.success && response.data.status === "operational";
  } catch (error) {
    console.error("OG Validator health check failed:", error);
    return false;
  }
};

/**
 * Export validation report as JSON
 */
export const exportAsJSON = (
  data: ValidationReport,
  filename?: string
): void => {
  const name =
    filename || `og-validation-${new Date().toISOString().split("T")[0]}.json`;
  const blob = new Blob([JSON.stringify(data, null, 2)], {
    type: "application/json",
  });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Generate shareable text report
 */
export const generateTextReport = (data: ValidationReport): string => {
  let report = `Open Graph Validation Report\n`;
  report += `${"=".repeat(50)}\n\n`;
  report += `URL: ${data.url}\n`;
  report += `Date: ${new Date(data.timestamp).toLocaleString()}\n`;
  report += `Status: ${data.isValid ? "VALID ✅" : "INVALID ❌"}\n\n`;

  report += `Summary:\n`;
  report += `- Total Tags: ${data.summary.totalTags}\n`;
  report += `- Required Tags: ${data.summary.requiredTagsPresent}/${data.summary.requiredTagsTotal}\n`;
  report += `- Errors: ${data.summary.errorsCount}\n`;
  report += `- Warnings: ${data.summary.warningsCount}\n\n`;

  if (Object.keys(data.tags).length > 0) {
    report += `Open Graph Tags:\n`;
    for (const [key, value] of Object.entries(data.tags)) {
      report += `- og:${key}: ${value.substring(0, 100)}${
        value.length > 100 ? "..." : ""
      }\n`;
    }
    report += `\n`;
  }

  if (data.errors.length > 0) {
    report += `Errors:\n`;
    data.errors.forEach((error, i) => {
      report += `${i + 1}. ${error}\n`;
    });
    report += `\n`;
  }

  if (data.warnings.length > 0) {
    report += `Warnings:\n`;
    data.warnings.forEach((warning, i) => {
      report += `${i + 1}. ${warning}\n`;
    });
    report += `\n`;
  }

  report += `Generated by Healthy SEO - Open Graph Validator\n`;
  return report;
};

/**
 * Save validation to localStorage history
 */
export const saveToHistory = (data: ValidationReport): void => {
  try {
    const history = JSON.parse(
      localStorage.getItem("og_validation_history") || "[]"
    );

    history.unshift({
      url: data.url,
      isValid: data.isValid,
      timestamp: data.timestamp,
      summary: data.summary,
    });

    // Keep only last 50 validations
    if (history.length > 50) {
      history.splice(50);
    }

    localStorage.setItem("og_validation_history", JSON.stringify(history));
  } catch (error) {
    console.error("Failed to save to history:", error);
  }
};

/**
 * Get validation history from localStorage
 */
export const getValidationHistory = (): any[] => {
  try {
    return JSON.parse(localStorage.getItem("og_validation_history") || "[]");
  } catch (error) {
    console.error("Failed to load history:", error);
    return [];
  }
};
